name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated to match Dart 3.x compatibility and null safety.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 # Updated to a null-safe version.
  rflutter_alert: ^2.0.4 # Updated to a null-safe version.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
