name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated to match Dart 3.x compatibility and null safety.

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  rename: ^3.1.0
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  remove_alpha_ios: true

flutter:
  uses-material-design: true
